In [1]:
import pandas as pd

In [8]:
data = {
    'apple':[2,3,4,5,6],
    'oranges': [8,4,7,5,4],
    'banana': [4,5,6,7,8]
}

In [9]:
data

{'apple': [2, 3, 4, 5, 6],
 'oranges': [8, 4, 7, 5, 4],
 'banana': [4, 5, 6, 7, 8]}

In [10]:
print(data)

{'apple': [2, 3, 4, 5, 6], 'oranges': [8, 4, 7, 5, 4], 'banana': [4, 5, 6, 7, 8]}

In [11]:
fruits = pd.DataFrame(data)

In [12]:
fruits

   apple  oranges  banana
0      2        8       4
1      3        4       5
2      4        7       6
3      5        5       7
4      6        4       8

In [14]:
print(fruits)

   apple  oranges  banana
0      2        8       4
1      3        4       5
2      4        7       6
3      5        5       7
4      6        4       8

In [18]:
purchases = pd.DataFrame(data, index = ['Jan', 'Rob', 'Lily', 'Dave', 'Kany'])

In [19]:
purchases

      apple  oranges  banana
Jan       2        8       4
Rob       3        4       5
Lily      4        7       6
Dave      5        5       7
Kany      6        4       8

In [20]:
purchases.loc['Rob']

apple      3
oranges    4
banana     5
Name: Rob, dtype: int64

In [22]:
df = pd.read_csv(r'C:\Users\REISD5\Downloads\Cashflow - January 26.csv')

In [23]:
df

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18
0,NaN,NaN,January,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,Overview,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,Cash Flow Actual,positive,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,Cash Flow Budget,negative,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,Spending Rate,"54,20%",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,Largest Expense,Gitarre + Setup,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,Cashflow,NaN,NaN,NaN,Bills,NaN,NaN,Expenses,NaN,NaN,Debt,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,Category,Budget,Actual,NaN,Category,Actual,NaN,Category,Actual,NaN,Category,Budget,Actual,NaN,NaN,NaN,Income,"1.024,00"
12,NaN,Income,"1.024,00","1.024,00",NaN,Netflix,"0,00",NaN,Transport,"0,00",NaN,Friends,"0,00","0,00",NaN,NaN,NaN,Left,"(91,00)"
13,NaN,Savings,"230,00","150,00",NaN,Spotify,"0,00",NaN,Groceries,"0,00",NaN,Family,"0,00","0,00",NaN,NaN,NaN,Spent,"1.115,00"
14,NaN,Bills,"45,00","45,00",NaN,Car,"0,00",NaN,Eating out,"37,00",NaN,Paypal,"30,00","30,00",NaN,NaN,NaN,NaN,NaN
15,NaN,Expenses,"555,00","555,00",NaN,Rent,"0,00",NaN,Coffee,"0,00",NaN,Auto,"300,00","0,00",NaN,NaN,NaN,Income,"1.024,00"
16,NaN,Debt,"330,00","30,00",NaN,IGBCE,"0,00",NaN,Fuel,"125,00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,Savings,"230,00"
17,NaN,Total,"(91,00)","289,00",NaN,DB,"45,00",NaN,Clothes,"0,00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bills,"45,00"
18,NaN,Spend,NaN,NaN,NaN,NaN,NaN,NaN,Gifts,"0,00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,Expenses,"555,00"
19,NaN,Income,NaN,NaN,NaN,NaN,NaN,NaN,Entertainment,"0,00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,Debt,"330,00"
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Car,"0,00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,Left,"(91,00)"
21,NaN,Category,Budget,Actual,NaN,NaN,NaN,NaN,Lunch @ Roche,"0,00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,NaN,Paycheck,"1.024,00","1.024,00",NaN,NaN,NaN,NaN,Parking,"1,00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,Total,"1.024,00"
23,NaN,Bonus,"0,00","0,00",NaN,NaN,NaN,NaN,Weihnachtsma.,"0,00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,Budget,"1.115,00"
24,NaN,Weihnachten,"0,00","0,00",NaN,NaN,NaN,NaN,London,"0,00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,Actual,"735,00"
25,NaN,Geburtstag,"0,00","0,00",NaN,NaN,NaN,NaN,vacation,"0,00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,NaN,Paypal,"0,00","0,00",NaN,NaN,NaN,NaN,Blumen,"0,00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,NaN,Total,"1.024,00","1.024,00",NaN,NaN,NaN,NaN,Lunch @ DH,"10,00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,DH Einkäufe,"15,00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,NaN,Savings,NaN,NaN,NaN,NaN,NaN,NaN,Wheinachtsgeschenk,"0,00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Rave,"5,00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,NaN,Category,Budget,Actual,NaN,NaN,NaN,NaN,Airpods,"0,00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,NaN,ETF's,"150,00","150,00",NaN,NaN,NaN,NaN,Wien,"0,00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,NaN,Car,"80,00","0,00",NaN,NaN,NaN,NaN,Backfischfest,"0,00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,NaN,Gold,"0,00","0,00",NaN,NaN,NaN,NaN,Kfz Steuer,"0,00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,NaN,Vacation,"0,00","0,00",NaN,NaN,NaN,NaN,Gitarre + Setup,"362,00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,NaN,Equate Plus,"0,00","0,00",NaN,NaN,NaN,NaN,Kreatin,"0,00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,NaN,Total,"230,00","150,00",NaN,Total,"45,00",NaN,Total,"555,00",NaN,Total,"330,00","30,00",NaN,NaN,NaN,NaN,NaN

In [24]:
df = pd.read_csv(r'C:\Users\REISD5\Downloads\Cashflow - January 26.csv', index_col=0)

In [25]:
df

,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18
NaN,NaN,January,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,Overview,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,Cash Flow Actual,positive,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,Cash Flow Budget,negative,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,Spending Rate,"54,20%",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,Largest Expense,Gitarre + Setup,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,Cashflow,NaN,NaN,NaN,Bills,NaN,NaN,Expenses,NaN,NaN,Debt,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,Category,Budget,Actual,NaN,Category,Actual,NaN,Category,Actual,NaN,Category,Budget,Actual,NaN,NaN,NaN,Income,"1.024,00"
NaN,Income,"1.024,00","1.024,00",NaN,Netflix,"0,00",NaN,Transport,"0,00",NaN,Friends,"0,00","0,00",NaN,NaN,NaN,Left,"(91,00)"
NaN,Savings,"230,00","150,00",NaN,Spotify,"0,00",NaN,Groceries,"0,00",NaN,Family,"0,00","0,00",NaN,NaN,NaN,Spent,"1.115,00"
NaN,Bills,"45,00","45,00",NaN,Car,"0,00",NaN,Eating out,"37,00",NaN,Paypal,"30,00","30,00",NaN,NaN,NaN,NaN,NaN
NaN,Expenses,"555,00","555,00",NaN,Rent,"0,00",NaN,Coffee,"0,00",NaN,Auto,"300,00","0,00",NaN,NaN,NaN,Income,"1.024,00"
NaN,Debt,"330,00","30,00",NaN,IGBCE,"0,00",NaN,Fuel,"125,00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,Savings,"230,00"
NaN,Total,"(91,00)","289,00",NaN,DB,"45,00",NaN,Clothes,"0,00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bills,"45,00"
NaN,Spend,NaN,NaN,NaN,NaN,NaN,NaN,Gifts,"0,00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,Expenses,"555,00"
NaN,Income,NaN,NaN,NaN,NaN,NaN,NaN,Entertainment,"0,00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,Debt,"330,00"
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Car,"0,00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,Left,"(91,00)"
NaN,Category,Budget,Actual,NaN,NaN,NaN,NaN,Lunch @ Roche,"0,00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,Paycheck,"1.024,00","1.024,00",NaN,NaN,NaN,NaN,Parking,"1,00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,Total,"1.024,00"
NaN,Bonus,"0,00","0,00",NaN,NaN,NaN,NaN,Weihnachtsma.,"0,00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,Budget,"1.115,00"
NaN,Weihnachten,"0,00","0,00",NaN,NaN,NaN,NaN,London,"0,00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,Actual,"735,00"
NaN,Geburtstag,"0,00","0,00",NaN,NaN,NaN,NaN,vacation,"0,00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,Paypal,"0,00","0,00",NaN,NaN,NaN,NaN,Blumen,"0,00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,Total,"1.024,00","1.024,00",NaN,NaN,NaN,NaN,Lunch @ DH,"10,00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,DH Einkäufe,"15,00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,Savings,NaN,NaN,NaN,NaN,NaN,NaN,Wheinachtsgeschenk,"0,00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Rave,"5,00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,Category,Budget,Actual,NaN,NaN,NaN,NaN,Airpods,"0,00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,ETF's,"150,00","150,00",NaN,NaN,NaN,NaN,Wien,"0,00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,Car,"80,00","0,00",NaN,NaN,NaN,NaN,Backfischfest,"0,00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,Gold,"0,00","0,00",NaN,NaN,NaN,NaN,Kfz Steuer,"0,00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,Vacation,"0,00","0,00",NaN,NaN,NaN,NaN,Gitarre + Setup,"362,00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,Equate Plus,"0,00","0,00",NaN,NaN,NaN,NaN,Kreatin,"0,00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,Total,"230,00","150,00",NaN,Total,"45,00",NaN,Total,"555,00",NaN,Total,"330,00","30,00",NaN,NaN,NaN,NaN,NaN

In [26]:
import json

In [27]:
df.head()

,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18
NaN,NaN,January,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,Overview,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,Cash Flow Actual,positive,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [28]:
df.tail()

,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18
NaN,Car,"80,00","0,00",NaN,NaN,NaN,NaN,Backfischfest,"0,00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,Gold,"0,00","0,00",NaN,NaN,NaN,NaN,Kfz Steuer,"0,00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,Vacation,"0,00","0,00",NaN,NaN,NaN,NaN,Gitarre + Setup,"362,00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,Equate Plus,"0,00","0,00",NaN,NaN,NaN,NaN,Kreatin,"0,00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,Total,"230,00","150,00",NaN,Total,"45,00",NaN,Total,"555,00",NaN,Total,"330,00","30,00",NaN,NaN,NaN,NaN,NaN

In [29]:
df.tail(2)

,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18
NaN,Equate Plus,"0,00","0,00",NaN,NaN,NaN,NaN,Kreatin,"0,00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,Total,"230,00","150,00",NaN,Total,"45,00",NaN,Total,"555,00",NaN,Total,"330,00","30,00",NaN,NaN,NaN,NaN,NaN

In [30]:
df.info()

<class 'pandas.DataFrame'>
Index: 38 entries, nan to nan
Data columns (total 18 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Unnamed: 1   30 non-null     str
 1   Unnamed: 2   26 non-null     str
 2   Unnamed: 3   21 non-null     str
 3   Unnamed: 4   0 non-null      float64
 4   Unnamed: 5   9 non-null      str
 5   Unnamed: 6   8 non-null      str
 6   Unnamed: 7   0 non-null      float64
 7   Unnamed: 8   28 non-null     str
 8   Unnamed: 9   27 non-null     str
 9   Unnamed: 10  0 non-null      float64
 10  Unnamed: 11  7 non-null      str
 11  Unnamed: 12  6 non-null      str
 12  Unnamed: 13  6 non-null      str
 13  Unnamed: 14  0 non-null      float64
 14  Unnamed: 15  0 non-null      float64
 15  Unnamed: 16  0 non-null      float64
 16  Unnamed: 17  12 non-null     str
 17  Unnamed: 18  12 non-null     str
dtypes: float64(6), str(12)
memory usage: 5.6 KB

In [32]:
df.shape

(38, 18)

In [34]:
temp_df = pd.concat([df, df])

In [35]:
temp_df.shape

(76, 18)

In [37]:
temp_df = temp_df.drop_duplicates()

In [38]:
temp_df.shape

(35, 18)

In [39]:
df.shape

(38, 18)

In [40]:
df_new = df.drop_duplicates()

In [41]:
df_new.shape

(35, 18)

In [42]:
df.drop_duplicates(inplace=True)

In [43]:
df.columns

Index(['Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5',
       'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10',
       'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14',
       'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18'],
      dtype='str')

In [46]:
df.rename(columns={'Unnamed: 1': 'Test'}, inplace=True)

In [47]:
df.head()

,Test,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18
NaN,NaN,January,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,Overview,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,Cash Flow Actual,positive,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,Cash Flow Budget,negative,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [48]:
df.columns = ['Test', 'Unna2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5',
       'Unnamed: 6', 'Unnamed: 7', 'Ued: 8', 'Unnamed: 9', 'Unnamed: 10',
       'Unnamed: 11', 'Uned: 12', 'amed: 13', 'Unnamed: 14',
       'Unnamed: 15', 'Unnamed: 16', 'Umed: 17', 'Unnamed: 18']

In [49]:
df.head()

,Test,Unna2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Ued: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Uned: 12,amed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Umed: 17,Unnamed: 18
NaN,NaN,January,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,Overview,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,Cash Flow Actual,positive,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,Cash Flow Budget,negative,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [50]:
df.columns = [col.lower() for col in df]

In [51]:
df.head()

,test,unna2,unnamed: 3,unnamed: 4,unnamed: 5,unnamed: 6,unnamed: 7,ued: 8,unnamed: 9,unnamed: 10,unnamed: 11,uned: 12,amed: 13,unnamed: 14,unnamed: 15,unnamed: 16,umed: 17,unnamed: 18
NaN,NaN,January,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,Overview,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,Cash Flow Actual,positive,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,Cash Flow Budget,negative,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [52]:
df.head(3)

,test,unna2,unnamed: 3,unnamed: 4,unnamed: 5,unnamed: 6,unnamed: 7,ued: 8,unnamed: 9,unnamed: 10,unnamed: 11,uned: 12,amed: 13,unnamed: 14,unnamed: 15,unnamed: 16,umed: 17,unnamed: 18
NaN,NaN,January,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,Overview,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [53]:
df.isnull()

,test,unna2,unnamed: 3,unnamed: 4,unnamed: 5,unnamed: 6,unnamed: 7,ued: 8,unnamed: 9,unnamed: 10,unnamed: 11,uned: 12,amed: 13,unnamed: 14,unnamed: 15,unnamed: 16,umed: 17,unnamed: 18
NaN,True,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
NaN,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
NaN,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
NaN,False,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
NaN,False,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
NaN,False,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
NaN,False,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
NaN,False,True,True,True,False,True,True,False,True,True,False,True,True,True,True,True,True,True
NaN,False,False,False,True,False,False,True,False,False,True,False,False,False,True,True,True,False,False
NaN,False,False,False,True,False,False,True,False,False,True,False,False,False,True,True,True,False,False
NaN,False,False,False,True,False,False,True,False,False,True,False,False,False,True,True,True,False,False
NaN,False,False,False,True,False,False,True,False,False,True,False,False,False,True,True,True,True,True
NaN,False,False,False,True,False,False,True,False,False,True,False,False,False,True,True,True,False,False
NaN,False,False,False,True,False,False,True,False,False,True,True,True,True,True,True,True,False,False
NaN,False,False,False,True,False,False,True,False,False,True,True,True,True,True,True,True,False,False
NaN,False,True,True,True,True,True,True,False,False,True,True,True,True,True,True,True,False,False
NaN,False,True,True,True,True,True,True,False,False,True,True,True,True,True,True,True,False,False
NaN,True,True,True,True,True,True,True,False,False,True,True,True,True,True,True,True,False,False
NaN,False,False,False,True,True,True,True,False,False,True,True,True,True,True,True,True,True,True
NaN,False,False,False,True,True,True,True,False,False,True,True,True,True,True,True,True,False,False
NaN,False,False,False,True,True,True,True,False,False,True,True,True,True,True,True,True,False,False
NaN,False,False,False,True,True,True,True,False,False,True,True,True,True,True,True,True,False,False
NaN,False,False,False,True,True,True,True,False,False,True,True,True,True,True,True,True,True,True
NaN,False,False,False,True,True,True,True,False,False,True,True,True,True,True,True,True,True,True
NaN,False,False,False,True,True,True,True,False,False,True,True,True,True,True,True,True,True,True
NaN,True,True,True,True,True,True,True,False,False,True,True,True,True,True,True,True,True,True
NaN,False,True,True,True,True,True,True,False,False,True,True,True,True,True,True,True,True,True
NaN,True,True,True,True,True,True,True,False,False,True,True,True,True,True,True,True,True,True
NaN,False,False,False,True,True,True,True,False,False,True,True,True,True,True,True,True,True,True
NaN,False,False,False,True,True,True,True,False,False,True,True,True,True,True,True,True,True,True
NaN,False,False,False,True,True,True,True,False,False,True,True,True,True,True,True,True,True,True
NaN,False,False,False,True,True,True,True,False,False,True,True,True,True,True,True,True,True,True
NaN,False,False,False,True,True,True,True,False,False,True,True,True,True,True,True,True,True,True
NaN,False,False,False,True,True,True,True,False,False,True,True,True,True,True,True,True,True,True
NaN,False,False,False,True,False,False,True,False,False,True,False,False,False,True,True,True,True,True

In [55]:
df.isnull().sum()

test            5
unna2           9
unnamed: 3     14
unnamed: 4     35
unnamed: 5     26
unnamed: 6     27
unnamed: 7     35
ued: 8          7
unnamed: 9      8
unnamed: 10    35
unnamed: 11    28
uned: 12       29
amed: 13       29
unnamed: 14    35
unnamed: 15    35
unnamed: 16    35
umed: 17       23
unnamed: 18    23
dtype: int64

In [59]:
df.dropna(inplace=True)

In [62]:
df['unnamed: 4'].describe()

count    0.0
mean     NaN
std      NaN
min      NaN
25%      NaN
50%      NaN
75%      NaN
max      NaN
Name: unnamed: 4, dtype: float64

In [63]:
df.corr()

,test,unna2,unnamed: 3,unnamed: 4,unnamed: 5,unnamed: 6,unnamed: 7,ued: 8,unnamed: 9,unnamed: 10,unnamed: 11,uned: 12,amed: 13,unnamed: 14,unnamed: 15,unnamed: 16,umed: 17,unnamed: 18
test,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
unna2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
unnamed: 3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
unnamed: 4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
unnamed: 5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
unnamed: 6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
unnamed: 7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ued: 8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
unnamed: 9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
unnamed: 10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
unnamed: 11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
uned: 12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
amed: 13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
unnamed: 14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
unnamed: 15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
unnamed: 16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
umed: 17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
unnamed: 18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN